### PR TITLE
Fix crashes when short answer question answers are undefined

### LINKED ISSUE #2532: Error in Quiz Preview Submission
### Describe the bug

The Quiz Preview submission freezes and shows errors in the console when I click on the score question icon to learn more about the score of the quiz question is calculated
image

#### To Reproduce

1. Create a Quiz exercise
2. Navigate to Preview and participate in the quiz
3. Submit the quiz in the preview
4. click on the question mark icon beside the score of one of the questions

#### Expected behavior

No freeze and instead a popup explaining the score calculation mechanism

### Environment

<details><pre>
 - OS: iOS and Windows
 - Browser: Chrome and Safari
</pre></details>

#### Output in Web Console

<details><pre>
161main.6a757a69bc7513b31f46.bundle.js:4 ERROR TypeError: Cannot read property 'text' of undefined
Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
</pre></details>

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context
Fixes #2532 which is a regression from #2528.

### Description
For some reason the expression evaluation in templates is different (that's also why we couldn't use the `??` operator), so this still crashed when trying to access `undefined.text` even after #2528. Maybe one of our experts knows an explanation.

### Steps for Testing
Simply create a new short answer question quiz. Then go in preview mode and submit without entering any answers. Without this fix a lot of warnings will be printed in the console (can freeze the browser) and the content will not be displayed correctly (since it crashes midway). Make sure short answer question quizzes work as expected during testing.

### Screenshots
Preview a quiz and submit without entering answers:
grafik
After submitting it will look broken and print warnings in the console without the fix:
grafik
With this fix everything displays correctly:
grafik

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
Tried different scenarios, all worked correctly

**Review by EneaGore — APPROVED** [review]
All looks good this time around.

**Review by krusche — APPROVED** [review]
