### ISSUE TITLE
Server administration Audits page throws ISE

### ISSUE THREAD

**Issue by tiffca** [ls1intum/Artemis#2344]
### Describe the bug

If you go to the Server Administration -> Audits URL and try to filter by dates, it throws an internal server error. 

#### To Reproduce

Tested on test server 1 and 3 
1. As an admin, go to Server Administration drop down menu and select the Audits menu
2. Click on the date button to try to select a date
3. See the Internal Server Error 

#### Expected behavior

Expected is that we should be able to see a sortable table of: Date, User, State, Extra data - even if it's empty. 

#### Screenshots

![audits-ise](https://user-images.githubusercontent.com/63906424/98240871-623b9b00-1f6a-11eb-87fc-0a019e1354d1.gif)

### Environment

<details><pre>
 - OS: MacOS
 - Browser: Chrome
</pre></details>

#### Output in Web Console

<details><pre>
 Failed to load resource: the server responded with a status of 500 ()
main.1cc642f18ab43c100064.bundle.js:2 ERROR v
(anonymous) @ main.1cc642f18ab43c100064.bundle.js:2
/management/audits?
</pre></details>

**Comment by tiffca** [comment]
Maybe related to #2334

**Comment by krusche** [comment]
Thanks for finding this issue.
It's not related to #2334 
We should fix this sooner than later.

**Comment by krusche** [comment]
This issue was caused by 44a27af

`PersistentAuditEvent` should not inherit from `DomainObject`, because `event_id` != `id`
