### PR TITLE
`Development`: Fix flaky open API generation and client build

### PR DESCRIPTION
**Pull request by florian-glombik**
### Summary
Optimizes the OpenAPI specification generation process to improve reliability and performance and fixes client-side compilation errors resulting from updated OpenAPI models. By disabling Liquibase migrations and using Hibernate's DDL-auto feature during the generation task, the execution time was reduced from ~3 minutes to under 50 seconds (~75% reduction). Additionally, improves the consistency of the generated spec.

#### General
- [x] This is a small issue that I tested locally
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.tum.de/developer/development-process#pr-naming-conventions).

### Motivation and Context
The OpenAPI spec generation (`./gradlew generateApiDocs`) was previously flaky and slow, often timing out on machines with limited resources. Since the client generation (`./gradlew openApiGenerate`) depends on a valid spec, it would frequently fail as well. This PR solves these issues by making the spec generation significantly faster and more robust (takes ~47 seconds now and is not flaky anymore). It also ensures the client remains compilable after the generator update by fixing type mismatches and import issues in the TypeScript code, some of which were introduced in commit #12496, while improving the schema quality through better DTO suffix pruning.

### Description
The following optimizations were implemented in `gradle/openapi.gradle`:
- **Accelerated Startup:** Disabled Liquibase migrations (`-Dspring.liquibase.enabled=false`) and enabled Hibernate `ddl-auto=create`. This bypasses expensive database initialization, reducing generation time by ~75%.
- **Reduced Overhead:** Disabled the Spring Boot banner and suppressed unnecessary logging noise during the process.

Improvements to the OpenAPI specification (`OpenAPIConfiguration.java`):
- **Robust DTO Pruning:** Enhanced the recursive pruning of "DTO" suffixes. The logic now correctly traverses `properties`, `allOf`, `anyOf`, and `oneOf`, and handles discriminator mappings to ensure consistent schema names across the entire specification.

The following client-side fixes and enhancements were implemented:
- **Programming Exercise Code Editor:** Updated mapping logic to handle both `RepositoryType` (UI) and the generated `RepositoryTypeEnum` (server), resolving type mismatches during code generation.
- **Quiz AI Generation:** Refactored `QuizQuestionRefinementResponse` into a proper discriminated union (`Success | Failure`). Updated the service to use type narrowing for better safety and fixed broken imports for generated refinement DTOs.
- **Model Updates:** Added support for optional `suggestedInlineFix` in `ArtifactLocation` and `CodeGenerationJobStart` models to support upcoming AI-assisted code fix features.

### Steps for Testing
Prerequisites:
- Local development environment with Java 25.

1. Run `./gradlew generateApiDocs -x webapp`
2. Verify that the task completes successfully in less than a minute.
3. Verify that `openapi/openapi.yaml` is updated.
4. Run `./gradlew openApiGenerate`
5. Verify that the client files are successfully generated without errors.
6. Run `npm run compile` and verify that the TypeScript code compiles without errors.
7. Verify that you have no diff to this branch

#### Code Review
- [x] Code Review 1
#### Manual Tests
- [x] Test 1

## Summary by CodeRabbit

* **New Features**
  * Optional inline code-fix suggestions can be attached to reported artifact locations.

* **Behavioral Changes**
  * Quiz-question refinement now uses explicit success/failure union types; only success responses apply refinements and failures are handled explicitly.
  * Code-generation requests accept additional backend-style repository type values.

* **Documentation**
  * Clarified quiz refinement request and bulk response descriptions.

* **Chores**
  * OpenAPI generator updated and OpenAPI pruning/DTO handling improved.

* **Tests**
  * Added unit test verifying failure propagation for refinement errors.

### CODE REVIEW

File: openapi/openapi.yaml [hunk 1]
```diff
@@ -1360,6 +1329,14 @@ components:
           type: string
           enum: [exercise, solution, tests, auxiliary, user]
         checkOnly: {type: boolean}
+    QuizQuestionRefinementResponse:
+      description: Discriminated response for a single quiz question refinement, either
+        a success with the refined question or a failure with an error message
+      discriminator: {propertyName: type}
+      oneOf: []
```
Comment (Claudia-Anthropica) [inline openapi/openapi.yaml]: @florian-glombik [critical] `oneOf: []` is empty — the discriminated response has no variants. Springdoc emits the inner records of `QuizQuestionRefinementResponseDTO` as components named `Success`/`Failure`, but the `@Schema(oneOf = {SuccessDTO.class, FailureDTO.class})` annotation references them by class name (`SuccessDTO`/`FailureDTO`), so the pruning step drops the dangling refs and leaves an empty array. Result: clients can't tell success from failure, and the Angular `QuizQuestionRefinementResponse` interface collapses to `{ type: string }`, which is what's breaking `quiz-ai-generation.service.ts`. Fix server-side by giving the inner records explicit names that match the `oneOf` refs, then regenerate.

File: openapi/openapi.yaml [hunk 2]
```diff
@@ -944,6 +946,16 @@ components:
...
+    Success:
+      allOf:
+      - type: object
+        properties:
+          reasoning: {type: string, description: Brief explanation of what was changed
+              during refinement, minLength: 1}
+          type: {type: string}
+      description: Successful refinement result containing the refined question and
+        an explanation of the changes
+      required: [question, reasoning]
```
Comment (Claudia-Anthropica) [inline openapi/openapi.yaml]: @florian-glombik [critical] `Success` declares `required: [question, reasoning]` but `properties` only defines `reasoning` and `type` — the `question: $ref(GeneratedQuizQuestion)` got dropped, so the regenerated `Success` TS type is missing the actual refined question and `quiz-ai-generation.service.ts` lines 57/94 fail with `Property 'question' does not exist on type 'QuizQuestionRefinementResponse'`. Same root cause as the `oneOf: []` above — fix the `@Schema` naming on the inner records and the field will come back through correctly.

File: src/main/webapp/app/openapi/model/quizQuestionRefinementResponse.ts [hunk 3]
```diff
@@ -7,15 +7,12 @@
...
- */
+
+
 /**
- * @type QuizQuestionRefinementResponse
  * Discriminated response for a single quiz question refinement, either a success with the refined question or a failure with an error message
- * @export
  */
-export type QuizQuestionRefinementResponse = QuizQuestionRefinementFailureDTO | QuizQuestionRefinementSuccessDTO;
+export interface QuizQuestionRefinementResponse {
```
Comment (Claudia-Anthropica) [inline src/main/webapp/app/openapi/model/quizQuestionRefinementResponse.ts]: @florian-glombik [critical] The discriminated union collapsed to `{ type: string }`, so `quiz-ai-generation.service.ts` no longer compiles — line 9 imports the deleted `quizQuestionRefinementSuccessDTO`, and lines 57/58/94/95 access `question`/`reasoning`/`TypeEnum.Success` that no longer exist on this type. CI is failing on exactly these errors. The root cause is the broken `oneOf` in the spec (see the yaml comment); once that's fixed and regenerated, this interface comes back as a proper union and the consumer just needs a small update for any renamed discriminator constants.

File: src/main/webapp/app/openapi/model/codeGenerationJobStart.ts [hunk 4]
```diff
@@ -9,9 +9,19 @@
  */
 
 
-import { RepositoryType } from 'app/programming/shared/code-editor/model/code-editor.model';
-
 export interface CodeGenerationJobStart { 
     jobId?: string;
-    repositoryType?: RepositoryType;
+    repositoryType?: CodeGenerationJobStart.RepositoryTypeEnum;
```
Comment (Claudia-Anthropica) [inline src/main/webapp/app/openapi/model/codeGenerationJobStart.ts:14]: @florian-glombik [high] `repositoryType` flipped from the shared `RepositoryType` enum (manually edited in #12333) to a local string-literal enum, which breaks `code-editor-instructor-and-editor-container.component.ts:487` with `Argument of type 'RepositoryTypeEnum' is not assignable to parameter of type 'RepositoryType'`. Either add a typeMapping in `gradle/openapi.gradle` so the generator emits the existing `RepositoryType` import again, or widen the consumer's `mapRepositoryTypeToCodeGenerationRequest` to accept both enums (their string values are identical, so a cast at the call site is enough).

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@florian-glombik The gradle speed-up (Liquibase off + ddl-auto=create + banner off) is a nice win. But the regenerated client is broken and CI is red on `client-compilation`, `client-tests`, `Build .war artifact`, and `Analyse`. The regenerated spec has an empty `oneOf: []` for `QuizQuestionRefinementResponse` and the `Success` schema is missing its `question` field, which collapses `QuizQuestionRefinementResponse` in TS to `{ type: string }` and breaks `quiz-ai-generation.service.ts` (deleted import + missing fields). Separately, `CodeGenerationJobStart.repositoryType` switched from the shared `RepositoryType` enum to a local literal enum and now fails to assign in `code-editor-instructor-and-editor-container.component.ts:487`. Probably worth landing a server-side `@Schema(name = "...")` fix on the inner records of `QuizQuestionRefinementResponseDTO` before regenerating, and either restoring the typeMapping to `RepositoryType` or updating the consumer.

File: openapi/openapi.yaml [hunk 5]
```diff
@@ -426,10 +426,10 @@ paths:
           content:
             application/json:
               schema: {$ref: '#/components/schemas/ConsistencyCheckResponse'}
-  /api/hyperion/courses/{courseId}/quiz-exercises/generate-questions:
+  /api/hyperion/courses/{courseId}/quiz-exercises/refine-question:
     post:
       tags: [hyperion-quiz-question-generation]
-      operationId: generateQuizQuestions
+      operationId: refineQuizQuestion
```
Comment (louis-heinrich) [inline openapi/openapi.yaml:432]: Is the reordering of the calls and schemas intended? For readability purposes I would like to keep them ordered as they currently are, if this has no implications for performance.

File: openapi/openapi.yaml [hunk 6]
```diff
@@ -944,6 +946,17 @@ components:
         applied: {type: boolean, description: Whether the action was successfully
             applied}
         summary: {type: string, description: Short summary of what was changed}
+    Success:
```
Comment (louis-heinrich) [inline openapi/openapi.yaml]: I would like to keep the name a bit more descriptive as `Success` is currently only used for the quizzes and contains the refined question.  I liked `QuizQuestionRefinementSuccess` :) (If needed for the tests add the DTO suffix) This also applies to `Failure`.

**Review by louis-heinrich — COMMENTED** [review]
First of all, nice changes. Thank you very much. Just two comments.

File: src/main/webapp/app/quiz/manage/update/quiz-ai-generation-modal/quiz-ai-generation.service.ts [hunk 7]
```diff
@@ -53,10 +54,16 @@ export class QuizAiGenerationService {
...
-            })),
+            map((response: QuizQuestionRefinementResponse) => {
+                if (response.type === 'success') {
+                    const success = response as Success;
+                    return {
+                        refinedQuestion: this.applyRefinedContentToQuestion(question, this.toGeneratedQuestion(success.question, 0)),
+                        reasoning: success.reasoning,
+                    };
+                }
+                throw new Error('Failed to refine question');
```
Comment (Claudia-Anthropica) [inline src/main/webapp/app/quiz/manage/update/quiz-ai-generation-modal/quiz-ai-generation.service.ts]: @florian-glombik [high] CI fails on `client-tests` because of this new failure branch (and the bulk equivalent on line 100, plus the new `RepositoryTypeEnum.Exercise/Solution/Tests` switch arms in `code-editor-instructor-and-editor-container.component.ts:514`) — the global vitest thresholds (lines 90.6, statements 90.43, etc.) drop just below the configured values. The single-refinement failure path here in particular has zero coverage: `refineMultipleChoiceQuestion` throws but no spec ever flushes `{ type: 'failure', error: '...' }`. Add one negative test in `quiz-ai-generation.service.spec.ts` and that should restore coverage.

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@florian-glombik The previous critical/high feedback was addressed cleanly — the spec now has a proper `oneOf: [Success, Failure]` with `question` back on `Success`, and the `RepositoryType` consumer was widened correctly. One thing left: `client-tests` is red because the new failure-path code in `quiz-ai-generation.service.ts` and the new switch arms in `code-editor-instructor-and-editor-container.component.ts` aren't exercised by any spec, dragging global coverage just under the configured thresholds. A small failure-case test should put it green.

File: openapi/openapi.yaml (hunk 5 above)
Comment (florian-glombik) [reply openapi/openapi.yaml:432]: the file is auto generated, content wise it did not change, did it?

File: openapi/openapi.yaml (hunk 6 above)
Comment (florian-glombik) [reply openapi/openapi.yaml]: It's auto generated aswell, with the more descriptive type, as subtype of the QuizRefinement the generator had problems as it generated invalid typescript

Comment (florian-glombik) [reply openapi/openapi.yaml]: Do you have a concrete sugestion on how to adjust `gradle/openapi.gradle` so that it works with the generator and is more descriptive?

**Review by Claudia-Anthropica — DISMISSED** [review]
@florian-glombik The failure-case test addresses the coverage gap on the new throw branch — looks good. Nice work.

**Review by Claudia-Anthropica — DISMISSED** [review]
@florian-glombik All previously flagged issues are addressed — spec, generated client, and the new `RepositoryType` switch arms look right, and the failure-branch test is in place. The unresolved `Success`/`Failure` schema naming thread with @louis-heinrich is worth resolving before merge though; the cleanest fix is `@Schema(name = "QuizQuestionRefinementSuccessDTO")` (and `…FailureDTO`) on the inner records of `QuizQuestionRefinementResponseDTO` so springdoc emits descriptive names instead of the generic flattened ones, and the existing DTO-suffix stripping then yields `QuizQuestionRefinementSuccess`/`Failure`.

**Review by krusche — DISMISSED** [review]

**Review by krusche — APPROVED** [review]

**Review by Claudia-Anthropica — DISMISSED** [review]
@florian-glombik The new SHA is just the develop merge — no substantive change vs the last revision I cleared. All earlier feedback is still addressed, CI looks clean. Approving.

File: gradle/openapi.gradle [hunk 8]
```diff
@@ -29,7 +29,10 @@
                 "-Dartemis.iris.enabled=true",
                 "-Dspringdoc.api-docs.enabled=true",
                 "-Dspringdoc.pre-loading-enabled=true",
-                "-Dspring.main.lazy-initialization=true"
+                "-Dspring.main.lazy-initialization=true",
+                "-Dspring.liquibase.enabled=false",
+                "-Dspring.jpa.hibernate.ddl-auto=create",
+                "-Dspring.main.banner-mode=off"
```
Comment (krusche) [inline gradle/openapi.gradle:39]: **[Low]** Document why `ddl-auto=create` is safe here

With `liquibase.enabled=false` + `ddl-auto=create`, the schema is materialized purely from JPA entities into the in-memory H2 DB at startup. That's what makes this fast, but it's also a divergence from how the server boots in CI/prod (Liquibase against PostgreSQL), so future readers would benefit from a one-line comment explaining that this combination is *only* used to spin up the Spring context far enough for springdoc to introspect controllers — no real persistence happens.

Non-blocking, just a maintainability hint.

File: gradle/openapi.gradle [hunk 9]
```diff
@@ -138,10 +142,10 @@
         Map<String, Object> mapValue,
         Map<String, Map<String, Object>> componentsMap
     ) {
-        if (mapValue.size() == 1 && mapValue.containsKey('$ref')) {
+        if (mapValue.containsKey('$ref')) {
```
Comment (krusche) [inline gradle/openapi.gradle]: **[Low]** Behavior change: `$ref` siblings no longer recursed

The old guard `mapValue.size() == 1 && mapValue.containsKey('$ref')` meant a node like `{$ref: …, description: …}` would fall through to normal recursion. After this change, *any* map with a `$ref` is short-circuited and returned as-is — its sibling keys are never visited.

OpenAPI 3.1 does allow siblings to `$ref` (and they're usually plain metadata), so this is fine in practice. Please double-check the generated `openapi.yaml` doesn't drop any node that the previous logic would have pruned, then either keep it as is or add a comment explaining the intent.

File: gradle/openapi.gradle [hunk 10]
```diff
@@ -169,6 +173,59 @@
...
+                if (!refPath?.startsWith('#/components/schemas/')) return
+
+                String subtypeName = refPath.substring('#/components/schemas/'.length())
+                Map<String, Object> subtype = schemas[subtypeName] as Map<String, Object>
+                if (subtype?.containsKey('allOf')) {
+                    flattenAllOfBackReference(subtype, schemaName)
+                }
+            }
+        }
+    }
```
Comment (krusche) [inline gradle/openapi.gradle:229]: **[Low]** `flattenDiscriminatorAllOfBackReferences` only walks one level

The function only flattens subtypes whose immediate parent has `oneOf + discriminator`. It does not recurse, so chains like *grandparent → parent → child* would only be partially flattened. That's enough for today's spec, but a short comment noting the assumption would prevent future surprises.

File: src/main/java/de/tum/cit/aet/artemis/OpenAPIConfiguration.java [hunk 11]
```diff
@@ -193,6 +185,27 @@ private void removeDTOSuffixesFromSchemaRecursively(Schema<?> schema) {
...
+            schema.getAnyOf().forEach(this::removeDTOSuffixesFromSchemaRecursively);
+        }
+
+        if (schema.getOneOf() != null) {
+            schema.getOneOf().forEach(this::removeDTOSuffixesFromSchemaRecursively);
+        }
+
+        if (schema.getDiscriminator() != null && schema.getDiscriminator().getMapping() != null) {
+            schema.getDiscriminator().getMapping()
+                    .replaceAll((key, value) -> value != null && value.endsWith("DTO") ? value.substring(0, value.length() - DTO_NUMBER_OF_CHARACTERS) : value);
```
Comment (krusche) [inline src/main/java/de/tum/cit/aet/artemis/OpenAPIConfiguration.java]: **[Low]** Discriminator-mapping suffix stripping

The values in `discriminator.mapping` are typically `$ref` strings ending with the schema name, so `value.endsWith("DTO")` will correctly trim `#/components/schemas/SuccessDTO` → `#/components/schemas/Success`. Works for the current spec.

Minor: a `value.startsWith("#/components/schemas/")` guard would make the intent clearer and prevent accidental suffix stripping on raw mapping values that happened to end in `DTO` for unrelated reasons.

File: src/main/webapp/app/openapi/model/success.ts [hunk 12]
```diff
@@ -13,19 +13,15 @@ import { GeneratedQuizQuestion } from './generatedQuizQuestion';
 /**
  * Successful refinement result containing the refined question and an explanation of the changes
  */
-export interface QuizQuestionRefinementSuccessDTO { 
-    type: QuizQuestionRefinementSuccessDTO.TypeEnum;
+export interface Success {
```
Comment (krusche) [inline src/main/webapp/app/openapi/model/success.ts]: **[Medium]** Generic schema name `Success` is collision-prone

This file is generated from the inner record `QuizQuestionRefinementResponseDTO.SuccessDTO`. After DTO-stripping, the schema name in the spec is just `Success`, which becomes a top-level export in the generated client.

As soon as anyone introduces another `SuccessDTO` inner class (e.g. for a different discriminated response), springdoc will collapse two unrelated types onto the same name. The fix is to add `@Schema(name = "QuizQuestionRefinementSuccess")` (and analogously `@Schema(name = "QuizQuestionRefinementFailure")`) on the inner records, or to rename the records themselves so the unqualified Java name carries enough context.

Also note: `type` is now `type?: string` (optional, untyped), so consumers cannot narrow `Failure | Success` based on `type === 'success'` without a cast — see the cast in `quiz-ai-generation.service.ts`.

File: src/main/webapp/app/openapi/model/quizQuestionRefinementFailure.ts [hunk 13]
```diff
@@ -12,18 +12,11 @@
 /**
  * Failed refinement result containing an error message
  */
-export interface QuizQuestionRefinementFailureDTO { 
-    type: QuizQuestionRefinementFailureDTO.TypeEnum;
+export interface Failure { 
     /**
      * Error message describing why the refinement failed
      */
     error: string;
```
Comment (krusche) [inline src/main/webapp/app/openapi/model/quizQuestionRefinementFailure.ts:19]: **[Medium]** Generic schema name `Failure` is collision-prone

See paired comment on `success.ts`. Same root cause and same recommended fix: scope the schema name via `@Schema(name = …)` on `QuizQuestionRefinementResponseDTO.FailureDTO`.

File: src/main/webapp/app/quiz/manage/update/quiz-ai-generation-modal/quiz-ai-generation.service.ts [hunk 14]
```diff
@@ -1,12 +1,13 @@
...
-import { QuizQuestionGenerationRequest } from 'app/openapi/model/quizQuestionGenerationRequest';
-import { QuizQuestionBulkRefinementRequest } from 'app/openapi/model/quizQuestionBulkRefinementRequest';
-import { QuizQuestionRefinementSuccessDTO } from 'app/openapi/model/quizQuestionRefinementSuccessDTO';
+import { HyperionQuizQuestionGenerationApiService } from '../../../../openapi/api/hyperionQuizQuestionGenerationApi.service';
+import { GeneratedQuizQuestion } from '../../../../openapi/model/generatedQuizQuestion';
+import { QuizQuestionRefinementRequest } from '../../../../openapi/model/quizQuestionRefinementRequest';
+import { QuizQuestionGenerationRequest } from '../../../../openapi/model/quizQuestionGenerationRequest';
+import { QuizQuestionBulkRefinementRequest } from '../../../../openapi/model/quizQuestionBulkRefinementRequest';
+import { QuizQuestionRefinementResponse } from '../../../../openapi/model/quizQuestionRefinementResponse';
+import { Success } from '../../../../openapi/model/success';
```
Comment (krusche) [inline src/main/webapp/app/quiz/manage/update/quiz-ai-generation-modal/quiz-ai-generation.service.ts]: **[Medium]** Inconsistent import style — should use `app/openapi/...` alias

This file is now the only place in `src/main/webapp/app/` using `../../../../openapi/...` imports for OpenAPI types. Every other file (including `quiz-ai-generation.service.spec.ts` right next to it) uses the `app/openapi/...` alias.

Please change these seven imports back to:
```ts
import { HyperionQuizQuestionGenerationApiService } from 'app/openapi/api/hyperionQuizQuestionGenerationApi.service';
import { GeneratedQuizQuestion } from 'app/openapi/model/generatedQuizQuestion';
import { QuizQuestionRefinementRequest } from 'app/openapi/model/quizQuestionRefinementRequest';
import { QuizQuestionGenerationRequest } from 'app/openapi/model/quizQuestionGenerationRequest';
import { QuizQuestionBulkRefinementRequest } from 'app/openapi/model/quizQuestionBulkRefinementRequest';
import { QuizQuestionRefinementResponse } from 'app/openapi/model/quizQuestionRefinementResponse';
import { Success } from 'app/openapi/model/success';
```

File: src/main/webapp/app/quiz/manage/update/quiz-ai-generation-modal/quiz-ai-generation.service.ts [hunk 15]
```diff
@@ -53,10 +54,16 @@ export class QuizAiGenerationService {
...
+            map((response: QuizQuestionRefinementResponse) => {
+                if (response.type === 'success') {
+                    const success = response as Success;
+                    return {
+                        refinedQuestion: this.applyRefinedContentToQuestion(question, this.toGeneratedQuestion(success.question, 0)),
+                        reasoning: success.reasoning,
+                    };
+                }
+                throw new Error('Failed to refine question');
+            }),
```
Comment (krusche) [inline src/main/webapp/app/quiz/manage/update/quiz-ai-generation-modal/quiz-ai-generation.service.ts:66]: **[Low]** Could surface the actual `Failure.error` for better UX

Correction on my earlier classification of this as a regression — it isn't. Develop's code had no failure branch at all (`map((response) => ({ refinedQuestion: …response.question, reasoning: response.reasoning }))`), so a server failure would silently produce undefined fields and likely crash inside `applyRefinedContentToQuestion`. The new code throwing a clean error is **strictly better** than develop.

The remaining suggestion is just a UX polish: include the server's `error` string so the instructor sees *why* refinement failed instead of the generic `"Failed to refine question"`.

```ts
import { Failure } from 'app/openapi/model/failure';
…
if (response.type === 'success') {
    const success = response as Success;
    return {
        refinedQuestion: this.applyRefinedContentToQuestion(question, this.toGeneratedQuestion(success.question, 0)),
        reasoning: success.reasoning,
    };
}
const failure = response as Failure;
throw new Error(failure.error ?? 'Failed to refine question');
```

Also non-blocking for the bulk path (~line 100), which silently drops failures from the `results` map — same situation as develop, just worth a TODO if you want surfacing later.

File: src/main/webapp/app/programming/manage/code-editor/instructor-and-editor-container/code-editor-instructor-and-editor-container.component.ts [hunk 16]
```diff
@@ -511,13 +511,16 @@ export class CodeEditorInstructorAndEditorContainerComponent extends CodeEditorI
      * @param repositoryType currently selected repository in the editor
      * @returns the matching supported generation repository, or `undefined` for unsupported tabs
      */
-    private mapRepositoryTypeToCodeGenerationRequest(repositoryType: RepositoryType): SupportedCodeGenerationRepositoryType | undefined {
+    private mapRepositoryTypeToCodeGenerationRequest(repositoryType: RepositoryType | CodeGenerationRequest.RepositoryTypeEnum): SupportedCodeGenerationRepositoryType | undefined {
```
Comment (krusche) [inline src/main/webapp/app/programming/manage/code-editor/instructor-and-editor-container/code-editor-instructor-and-editor-container.component.ts]: **[Nit]** Signature mentions `CodeGenerationRequest.RepositoryTypeEnum` but caller passes `CodeGenerationJobStart.RepositoryTypeEnum`

The sole caller (line 487) passes `res.repositoryType` from a `CodeGenerationJobStart` response. The signature here lists `CodeGenerationRequest.RepositoryTypeEnum`. Both are the same string-literal union (`'exercise' | 'solution' | 'tests' | 'auxiliary' | 'user'`), so TS accepts it today with no cast — purely a readability/intent nit, not a real bug. Could be tightened later with a shared type alias if either enum diverges.

File: openapi/openapi.yaml [hunk 17]
```diff
@@ -908,16 +908,18 @@ components:
           type: string
           description: Question type
           enum: [single-choice, multiple-choice, true-false]
-        title: {type: string, description: Question title, minLength: 1}
-        questionText: {type: string, description: Question text, minLength: 1}
+        title: {type: string, description: Question title, maxLength: 500, minLength: 0}
```
Comment (krusche) [inline openapi/openapi.yaml]: **[Medium]** `minLength` regressed from 1 → 0 for `@NotBlank` fields

`title`, `questionText`, `hint`, `explanation` here (and `refinementPrompt` further down) all annotate `@NotBlank` / `@Size(max=…)` on the server. Previously the spec correctly emitted `minLength: 1`; the regenerated spec emits `minLength: 0`, which contradicts server-side validation and weakens the generated client.

The same regression hits `QuizQuestionBulkRefinementRequest.questions` (`@NotEmpty` → `minItems: 0`). Worth investigating whether the new boot configuration (`liquibase.enabled=false` + `ddl-auto=create` + `lazy-initialization`) or the openapi-generator bump from 7.20→7.21 dropped the bean-validation introspection. If it can't be restored quickly, please call this out in the PR description so it's not a silent contract change.

File: openapi/openapi.yaml [hunk 18]
```diff
@@ -1360,6 +1329,16 @@ components:
           type: string
           enum: [exercise, solution, tests, auxiliary, user]
         checkOnly: {type: boolean}
+    QuizQuestionRefinementResponse:
+      description: Discriminated response for a single quiz question refinement, either
+        a success with the refined question or a failure with an error message
+      discriminator: {propertyName: type}
+      oneOf:
+      - {$ref: '#/components/schemas/Success'}
+      - {$ref: '#/components/schemas/Failure'}
```
Comment (krusche) [inline openapi/openapi.yaml]: **[Medium]** Discriminator no longer pinned to literal values

Previously the spec had `mapping: {success: …SuccessDTO, failure: …FailureDTO}` AND each subtype declared `type: {enum: [success]}` / `[failure]`. Now the parent has only `discriminator: {propertyName: type}` (no `mapping`) and each subtype declares `type: {type: string}` — i.e. the literal values are gone.

Clients can therefore no longer narrow `QuizQuestionRefinementResponse` on `type === 'success'` without an explicit cast (which is exactly what `quiz-ai-generation.service.ts` now does). If the springdoc upgrade dropped this, consider re-adding it via `@Schema(allowableValues = {"success"})` on the `type` field of each subtype, or a custom `OpenApiCustomizer` step that re-injects the discriminator mapping.

**Review by krusche — CHANGES_REQUESTED** [review]
Thanks for the focused improvements to the OpenAPI generation pipeline — the move to `liquibase.enabled=false` + `ddl-auto=create` is a great win, and the recursive DTO-suffix pruning across `properties`/`allOf`/`anyOf`/`oneOf`/`discriminator` is a real fix. The build/runtime story is sound.

**Correction to my earlier review:** I called the new failure-handling in `quiz-ai-generation.service.ts` a *regression*. It isn't — develop had no failure branch at all and would have crashed on a `Failure` payload, so the new explicit `throw` is strictly better. The remaining feedback there is just "include `Failure.error` in the message" (downgraded to Low). The signature-mismatch note on `mapRepositoryTypeToCodeGenerationRequest` is a Nit, not a Low — both enums are the same string-literal union, so TS accepts the call today.

The verified Medium issues that still motivate **REQUEST_CHANGES**:

### Medium (please address before merge)
- **Generic schema names `Success` / `Failure`** — verified new in this PR (develop has `quizQuestionRefinementSuccessDTO.ts` / `…FailureDTO.ts`). The Java DTO is unchanged, so springdoc's naming changed under the new boot config / generator version and emitted unqualified inner-class names. Annotate the inner records with `@Schema(name = "QuizQuestionRefinementSuccess"/"…Failure")` (or rename them) so the generated TS exports don't sit at top-level under such collision-prone names.
- **Validation hints regressed in `openapi.yaml`** — verified by diffing develop: `title`, `questionText`, `refinementPrompt` went from `minLength: 1` → `minLength: 0`, and `QuizQuestionBulkRefinementRequest.questions` from `minItems: 1` → `0`, despite `@NotBlank` / `@NotEmpty` being unchanged on the Java side. Server enforcement is fine; only the generated client loses the constraint. Worth pinning down whether it was the springdoc/generator bump or the new boot flags before this lands.
- **Lost literal type discriminator** — verified by diffing develop: the old spec had `discriminator.mapping` plus `enum: [success]` / `enum: [failure]` on each subtype. The new spec has neither — both subtypes carry `type: {type: string}`, which is why the new TS has to do `response as Success`. Worth re-adding via `@Schema(allowableValues = {"success"})` on each subtype's `type` field, or a customizer step that re-injects the mapping.
- **Relative imports in `quiz-ai-generation.service.ts`** — verified: develop uses `app/openapi/...` aliases; this PR rewrote them to `../../../../openapi/...`. The sibling `*.spec.ts` still uses `app/openapi/...`. Hand-edit, not generator output. Please revert.

### Low / Nit
- `pruneInvalidReferences` lost the `size() == 1` guard around `$ref`. OpenAPI 3.1 allows `$ref` siblings, so OK in practice — but worth verifying the regenerated spec doesn't drop nodes the old logic would have pruned.
- `flattenDiscriminatorAllOfBackReferences` walks only one level — fine for today, just worth a comment noting the assumption.
- `mapRepositoryTypeToCodeGenerationRequest` parameter type (Nit, see inline).
- `quiz-ai-generation.service.ts` could include `Failure.error` in the thrown error for better UX (Low — strictly better than develop already, see inline).

The build-pipeline changes are great. With the four Medium items resolved this is good to merge.

File: src/main/webapp/app/quiz/manage/update/quiz-ai-generation-modal/quiz-ai-generation.service.ts (hunk 15 above)
Comment (florian-glombik) [reply src/main/webapp/app/quiz/manage/update/quiz-ai-generation-modal/quiz-ai-generation.service.ts:66]: We want to surface an actionable message, but now we also translate it

File: openapi/openapi.yaml (hunk 6 above)
Comment (florian-glombik) [reply openapi/openapi.yaml]: I adjusted the names in src/main/java/de/tum/cit/aet/artemis/hyperion/dto/QuizQuestionRefinementResponseDTO.java from which the code is generated, so it is more unique now 👍

**Review by Claudia-Anthropica — APPROVED** [review]
@florian-glombik @krusche's medium feedback has been addressed across the new commits — `Success`/`Failure` schemas renamed to `QuizQuestionRefinementSuccess`/`Failure`, `minLength: 1` restored on the `@NotBlank` fields, the `flatten…BackReferences` walker now recurses through chains, imports unified to `app/openapi/...`, signature aligned with the actual caller, and the subtype `type` fields now carry literal `enum: [success]`/`[failure]` so the TS narrowing in `quiz-ai-generation.service.ts` works without a cast. CI on this SHA is clean (the E2E failure shown in the PR checks ran on `develop`, not on this branch). Approving.

File: openapi/openapi.yaml (hunk 6 above)
Comment (louis-heinrich) [reply openapi/openapi.yaml]: Thank you! Nice solution 👍

File: openapi/openapi.yaml (hunk 5 above)
Comment (louis-heinrich) [reply openapi/openapi.yaml:432]: Interesting, I usually write the openapi first (as its less definitions to write) and then let the other code be generated from it. If it is auto-generated, this is fine :)

**Review by krusche — APPROVED** [review]
